name: Deploy to UAT1

on:
  workflow_call:
    inputs:
      NAME:
        required: true
        type: string

env:
  NAME: "child"
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: hello world
      run: echo "hello ${{inputs.NAME}}"
      
